# Generated by Django 3.1 on 2020-09-16 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 2, 44, 24, 730374, tzinfo=utc), verbose_name='date ended'),
            preserve_default=False,
        ),
    ]
